#!/usr/bin/env python3

from pathlib import Path
import json
import re
from collections import Counter

ROOT = Path(__file__).resolve().parent.parent

PROBLEM_RE = re.compile(r"^\d{1,6}-.+")

LANG_EXT = {
    ".java": "Java",
    ".cpp": "C++",
    ".c": "C",
    ".py": "Python",
    ".js": "JavaScript",
    ".ts": "TypeScript",
    ".go": "Go",
    ".rs": "Rust",
    ".kt": "Kotlin",
    ".swift": "Swift",
    ".rb": "Ruby",
    ".php": "PHP",
    ".sql": "SQL",
}

IGNORE_DIRS = {
    ".git",
    ".github",
    "08-Templates",
    "09-Statistics",
    "10-Automation",
    "Topics",
    "assets",
    "scripts",
}

problems = []

for directory in ROOT.iterdir():
    if not directory.is_dir():
        continue

    if directory.name in IGNORE_DIRS:
        continue

    if not PROBLEM_RE.match(directory.name):
        continue

    match = re.match(r"^(\d{1,6})-(.+)$", directory.name)
    if not match:
        continue

    problem_id = int(match.group(1))
    slug = match.group(2)

    solution_files = []

    for file in directory.rglob("*"):
        if not file.is_file():
            continue

        if file.suffix.lower() in LANG_EXT:
            solution_files.append(file)

    if not solution_files:
        continue

    languages = sorted(
        {LANG_EXT[f.suffix.lower()] for f in solution_files}
    )

    text = ""

    readme = directory / "README.md"
    if readme.exists():
        try:
            text = readme.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            text = ""

    difficulty = "Unknown"

    for d in ("Easy", "Medium", "Hard"):
        if re.search(rf"\bDifficulty\s*:\s*{d}\b", text, re.I):
            difficulty = d
            break

    if difficulty == "Unknown":
        lower = text.lower()

        if re.search(r"\b(easy)\b", lower):
            difficulty = "Easy"
        elif re.search(r"\b(medium)\b", lower):
            difficulty = "Medium"
        elif re.search(r"\b(hard)\b", lower):
            difficulty = "Hard"

    problems.append({
        "id": problem_id,
        "slug": slug,
        "directory": directory.name,
        "difficulty": difficulty,
        "languages": languages,
        "solution_count": len(solution_files),
    })

problems.sort(key=lambda x: x["id"])

total = len(problems)

difficulty = Counter(p["difficulty"] for p in problems)

languages = Counter()
for p in problems:
    for lang in p["languages"]:
        languages[lang] += 1

language_order = [
    "Java",
    "C++",
    "SQL",
    "Python",
    "JavaScript",
    "TypeScript",
    "C",
    "Go",
    "Rust",
    "Kotlin",
    "Swift",
    "Ruby",
    "PHP",
]

language_rows = []

for lang in language_order:
    if languages[lang]:
        language_rows.append((lang, languages[lang]))

for lang in sorted(languages):
    if lang not in {x[0] for x in language_rows}:
        language_rows.append((lang, languages[lang]))

progress = f"""# 📊 LeetCode Progress

> Automatically generated by `scripts/update_progress_v5.py`.

## Overall

| Metric | Count |
|---|---:|
| **Total Problems** | **{total}** |
| Total Solution Files | **{sum(p["solution_count"] for p in problems)}** |

## Difficulty

| Difficulty | Solved |
|---|---:|
| 🟢 Easy | {difficulty["Easy"]} |
| 🟡 Medium | {difficulty["Medium"]} |
| 🔴 Hard | {difficulty["Hard"]} |
| ⚪ Unknown | {difficulty["Unknown"]} |

## Languages

| Language | Problems |
|---|---:|
"""

for lang, count in language_rows:
    progress += f"| {lang} | {count} |\n"

progress += """
## Problem Inventory

| # | Problem | Difficulty | Languages |
|---:|---|---|---|
"""

for p in problems:
    title = p["slug"].replace("-", " ").title()
    langs = ", ".join(p["languages"])
    progress += (
        f'| {p["id"]} | {title} | {p["difficulty"]} | {langs} |\n'
    )

progress += "\n_Last updated automatically._\n"

(ROOT / "PROGRESS.md").write_text(progress, encoding="utf-8")

stats = {
    "total_problems": total,
    "total_solution_files": sum(p["solution_count"] for p in problems),
    "difficulty": dict(difficulty),
    "languages": dict(languages),
    "problems": problems,
}

(ROOT / "09-Statistics" / "PROGRESS.json").write_text(
    json.dumps(stats, indent=2, ensure_ascii=False) + "\n",
    encoding="utf-8",
)

print(f"✅ Progress generated: {total} problems")
print(f"   Difficulty: {dict(difficulty)}")
print(f"   Languages : {dict(languages)}")
